version: '3'
services:
  morphocluster:
    container_name: morphocluster
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./data:/data
  postgres:
    #image: "postgres:12-alpine"
    environment:
      POSTGRES_USER: morphocluster
      POSTGRES_PASSWORD: morphocluster
      POSTGRES_DB: morphocluster
    ports:
      - "5432:5432" # Remove in production
    # volumes:
    #   - morphocluster-pgsql:/var/lib/postgresql/data
    build: docker/postgresql

# volumes:
#   morphocluster-data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /data/morphocluster/data
#   morphocluster-pgsql:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /data/morphocluster/pgsql